metadata:
  total_jobs: 9
  problem_type: scattering
  description: 9-case parameter sweep
jobs:
- job_id: 0
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: sphere
  incident_direction:
  - 0
  - 0
  - 1
  incident_polarization:
  - 1
  - 0
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  sphere_radius: 0.1
- job_id: 1
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: sphere
  incident_direction:
  - 1
  - 0
  - 0
  incident_polarization:
  - 0
  - 1
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  sphere_radius: 0.1
- job_id: 2
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: sphere
  incident_direction:
  - 0.5774
  - 0.5774
  - 0.5774
  incident_polarization:
  - 1
  - 0
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  sphere_radius: 0.1
- job_id: 3
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: ellipsoid
  incident_direction:
  - 0
  - 0
  - 1
  incident_polarization:
  - 1
  - 0
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  ellipsoid_semi_axis_a: 0.15
  ellipsoid_semi_axis_b: 0.225
  ellipsoid_semi_axis_c: 0.3
  ellipsoid_orientation: z
- job_id: 4
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: ellipsoid
  incident_direction:
  - 1
  - 0
  - 0
  incident_polarization:
  - 0
  - 1
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  ellipsoid_semi_axis_a: 0.15
  ellipsoid_semi_axis_b: 0.225
  ellipsoid_semi_axis_c: 0.3
  ellipsoid_orientation: z
- job_id: 5
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: spheroid
  incident_direction:
  - 0
  - 0
  - 1
  incident_polarization:
  - 1
  - 0
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  spheroid_equatorial_radius: 0.3
  spheroid_polar_radius: 0.5
- job_id: 6
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: spheroid
  incident_direction:
  - 1
  - 0
  - 0
  incident_polarization:
  - 0
  - 1
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  spheroid_equatorial_radius: 0.3
  spheroid_polar_radius: 0.5
- job_id: 7
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: spheroid
  incident_direction:
  - 0
  - 0
  - 1
  incident_polarization:
  - 1
  - 0
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  spheroid_equatorial_radius: 0.5
  spheroid_polar_radius: 0.3
- job_id: 8
  problem_type: scattering
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: spheroid
  incident_direction:
  - 1
  - 0
  - 0
  incident_polarization:
  - 0
  - 1
  - 0
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  spheroid_equatorial_radius: 0.5
  spheroid_polar_radius: 0.3
