metadata:
  total_jobs: 12
  problem_type: antenna
  description: 12-case parameter sweep
jobs:
- job_id: 0
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 0.3
  dipole_radius: 0.01
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L0.3\u03BB"
  radius_label: "r0.010\u03BB"
- job_id: 1
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 0.3
  dipole_radius: 0.02
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L0.3\u03BB"
  radius_label: "r0.020\u03BB"
- job_id: 2
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 0.5
  dipole_radius: 0.005
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L0.5\u03BB"
  radius_label: "r0.005\u03BB"
- job_id: 3
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 0.5
  dipole_radius: 0.01
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L0.5\u03BB"
  radius_label: "r0.010\u03BB"
- job_id: 4
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 0.5
  dipole_radius: 0.015
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L0.5\u03BB"
  radius_label: "r0.015\u03BB"
- job_id: 5
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 0.5
  dipole_radius: 0.01
  dipole_orientation: x
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L0.5\u03BB"
  radius_label: "r0.010\u03BB"
- job_id: 6
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 1.0
  dipole_radius: 0.01
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L1.0\u03BB"
  radius_label: "r0.010\u03BB"
- job_id: 7
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 1.0
  dipole_radius: 0.015
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L1.0\u03BB"
  radius_label: "r0.015\u03BB"
- job_id: 8
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 1.5
  dipole_radius: 0.01
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L1.5\u03BB"
  radius_label: "r0.010\u03BB"
- job_id: 9
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 1.5
  dipole_radius: 0.015
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L1.5\u03BB"
  radius_label: "r0.015\u03BB"
- job_id: 10
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 2.0
  dipole_radius: 0.01
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L2.0\u03BB"
  radius_label: "r0.010\u03BB"
- job_id: 11
  problem_type: antenna
  wavelength: 1.0
  wavenumber: 6.283185307179586
  geometry_type: dipole
  dipole_length: 2.0
  dipole_radius: 0.015
  dipole_orientation: z
  source_amplitude: 1.0
  feed_position: center
  domain_radius: 2.0
  pml_width: 0.25
  max_mesh_size: 0.06666666666666667
  fes_order: 3
  solver_method: direct
  save_solution: true
  length_label: "L2.0\u03BB"
  radius_label: "r0.015\u03BB"
